#!/bin/bash
apply() {
  namespace=$1
  cat settings-$namespace | while read key value; do
    adb shell settings put $namespace $key "$value"
  done
}

generate() {
  namespace=$1
  cat settings-$namespace | while read key value; do
    echo "$key $(adb shell settings get $namespace $key | tr -d '\015')" >> settings-$namespace.gen
  done
  mv settings-$namespace.gen settings-$namespace
}

pm-enable() {
  adb shell su -c 'mkdir -p /data/local/userinit.d'
  adb shell su -c 'chmod 750 /data/local/userinit.d'
  adb shell su -c "echo '#!/system/bin/sh' > /data/local/userinit.d/00pm-enable"
  adb shell su -c 'chmod 750 /data/local/userinit.d/00pm-enable'
  cat pm-enable | while read key; do
    adb shell su -c "pm enable $key"
    adb shell su -c "echo pm enable $key >> /data/local/userinit.d/00pm-enable"
  done
}

"$@"
